spring.application.name=ecom
server.port=8080

# MongoDB URI (point to your ecom DB)
spring.data.mongodb.uri=mongodb://localhost:27017/ecom
spring.data.mongodb.database=ecom

# optional: show mongo queries
spring.data.mongodb.logging.level=INFO
